// Generated by CoffeeScript 2.7.0
(function() {
  // -*- coffee -*-

  //  file; src/client/index.coffee

  var WS_RMI_Client, WS_RMI_Connection, WS_RMI_Object, random_id;

  
  ({WS_RMI_Connection, WS_RMI_Object, random_id} = require('../common'));

  ({WS_RMI_Client} = require('../lib/ws_rmi_client'));

  
  module.exports = {WS_RMI_Client, WS_RMI_Connection, WS_RMI_Object, random_id};

}).call(this);
