// Generated by CoffeeScript 2.7.0
(function() {
  //!/usr/bin/env coffee

  //  file: /src/test/examples/index.coffee
  //  package: ws-rmi

  var stack;

  stack = require('./stack');

  module.exports = {stack};

}).call(this);
