// Generated by CoffeeScript 2.7.0
(function() {
  //!/usr/bin/env coffee

  //  file: /src/test/examples/stack.coffee
  //  package: ws-rmi

  var Logger, Stack, random_id;

  ({random_id, Logger} = require('armazilla-util'));

  Stack = class Stack {
    constructor() {
      this.push = this.push.bind(this);
      this.pop = this.pop.bind(this);
      this.id = random_id(this);
      this.name = 'stack';
      this.stack = [];
    }

    push(x) {
      return new Promise((resolve, reject) => {
        var error;
        try {
          resolve(this.stack.push(x));
          return console.log(this.stack);
        } catch (error1) {
          error = error1;
          return reject(error);
        }
      });
    }

    pop() {
      return new Promise((resolve, reject) => {
        var error;
        try {
          resolve(this.stack.pop());
          return console.log(this.stack);
        } catch (error1) {
          error = error1;
          return reject(error);
        }
      });
    }

  };

  module.exports = {
    Class: Stack,
    method_names: ['push', 'pop']
  };

}).call(this);
