// Generated by CoffeeScript 2.4.1
(function() {
  //!/usr/bin/env coffee

  //  settings.coffee

  var ipc_options, local_options, log, log_options, nginx_options, remote_options, util;

  util = require('util');

  log_options = {
    colors: true,
    depth: null
  };

  log = function(...xs) {
    var i, len, results, x;
    console.log("\n");
    results = [];
    for (i = 0, len = xs.length; i < len; i++) {
      x = xs[i];
      if (typeof x === 'string') {
        results.push(console.log(x));
      } else {
        results.push(console.log(util.inspect(x, log_options)));
      }
    }
    return results;
  };

  nginx_options = {
    protocol: 'ws+unix',
    port: null,
    host: null,
    uid: void 0, // defaults to user starting server
    gid: 33, // group 'www-data'
    mode: 0o660,
    path: '/tmp/stack-rmi',
    log_level: 2,
    log: log
  };

  ipc_options = {
    protocol: 'ws+unix',
    port: null,
    host: null,
    path: '/tmp/stack-rmi',
    log_level: 2,
    log: log
  };

  local_options = {
    protocol: 'ws',
    port: 8087,
    path: '',
    host: 'localhost',
    log_level: 1,
    log: log
  };

  remote_options = {
    protocol: 'wss',
    port: 443,
    host: 'alcarruth.net',
    path: '/wss/tickets_coffee',
    log_level: 1,
    log: console.log
  };

  exports.local_options = local_options;

  exports.remote_options = remote_options;

  exports.ipc_options = ipc_options;

}).call(this);
