// Generated by CoffeeScript 2.4.1
(function() {
  //!/usr/bin/env coffee

  var conf, generate_nginx_conf, spec;

  generate_nginx_conf = function(spec) {
    var access_log, auth, error_log, host, name, path, port;
    // required
    name = spec.name;
    path = spec.path;
    access_log = spec.access_log;
    error_log = spec.error_log;
    // optional
    host = spec.host || 'localhost';
    port = spec.port || 8080;
    auth = spec.auth || {
      type: null,
      path: null
    };
    return `\nlocation ${path} {\n\n    ${auth.type};\n    ${auth.path};\n\n    # mozilla sends a different origin than chrome\n    proxy_http_version 1.1;\n    proxy_read_timeout 3600s;\n\n    # proxy to port ${port}\n    proxy_pass http://${host}:${port}/;\n    proxy_set_header Upgrade $http_upgrade;\n    proxy_set_header Connection "upgrade";\n\n    proxy_redirect http://${host}:${port}/ ${path};\n    proxy_set_header X-Forwarded-Host $host:$server_port;\n    proxy_set_header X-Forwarded-Server $host;\n\n    access_log ${access_log};\n    error_log ${error_log};\n}`;
  };

  spec = {
    name: 'web-tix',
    path: '/wss/tickets_coffee',
    access_log: '/var/log/alcarruth/tickets.log',
    error_log: '/var/log/alcarruth/tickets.err',
    host: 'localhost',
    port: 8086,
    auth: {
      type: 'auth_basic "alcarruth"',
      path: 'auth_basic_user_file /etc/nginx/htpasswd'
    }
  };

  if (module.parent) {
    exports.generate_nginx_conf = generate_nginx_conf;
  } else {
    conf = generate_nginx_conf(spec);
    console.log(conf);
  }

}).call(this);
