// Generated by CoffeeScript 2.7.0
(function() {
  // -*- coffee -*-

  //  file: /src/index.coffee
  //  package: ws-rmi

  var Logger, RMI_Client, RMI_Connection, RMI_Object, RMI_Object_Registry, RMI_Server, RMI_Stub, RMI_Stub_Registry, random_id, test;

  // RMI_Proxy
  
  ({random_id, Logger, RMI_Client, RMI_Server, RMI_Connection, RMI_Object, RMI_Stub, RMI_Object_Registry, RMI_Stub_Registry} = require('./lib'));

  test = require('./test');

  // RMI_Proxy
  module.exports = {random_id, Logger, RMI_Client, RMI_Server, RMI_Connection, RMI_Object, RMI_Stub, RMI_Object_Registry, RMI_Stub_Registry, test};

}).call(this);
