// Generated by CoffeeScript 2.7.0
(function() {
  // -*- coffee -*-

  //  file: /src/server/index.coffee
  //  package: ws-rmi

  var RMI_Connection, RMI_Object, RMI_Object_Registry, RMI_Server, RMI_Stub, RMI_Stub_Registry;

  ({RMI_Server} = require('../lib/rmi_server'));

  ({RMI_Connection} = require('../lib/rmi_connection'));

  ({RMI_Object, RMI_Stub} = require('../lib/rmi_object'));

  ({RMI_Object_Registry, RMI_Stub_Registry} = require('../lib/rmi_registry'));

  module.exports = {RMI_Server, RMI_Connection, RMI_Object, RMI_Stub, RMI_Object_Registry, RMI_Stub_Registry};

}).call(this);
