// Generated by CoffeeScript 2.7.0
(function() {
  // -*- coffee -*-

  //  file: /src/test/browser_client.coffee
  //  package: ws-rmi

  var Test_Client, browser_client;

  ({Test_Client} = require('./client'));

  browser_client = new Test_Client('remote');

  browser_client.add_example('stack');

  if (typeof window !== "undefined" && window !== null) {
    window.client = browser_client;
  } else {
    module.exports = browser_client;
  }

}).call(this);
