// Generated by CoffeeScript 2.7.0
(function() {
  // -*- coffee -*-

  //  file: /src/test/client.coffee
  //  package: ws-rmi

  var RMI_Client, RMI_Connection, Test_Client, examples, options_choices,
    boundMethodCheck = function(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new Error('Bound instance method accessed before binding'); } };

  ({RMI_Client, RMI_Connection} = require('../client'));

  options_choices = require('./options');

  examples = require('./examples');

  Test_Client = class Test_Client extends RMI_Client {
    constructor(type = 'ipc') {
      var options;
      options = options_choices[type];
      super({options});
      this.add_example = this.add_example.bind(this);
    }

    add_example(name = 'stack') {
      var spec;
      boundMethodCheck(this, Test_Client);
      spec = examples[name];
      return this.add_object({
        obj: new spec.Class(),
        method_names: spec.method_names
      });
    }

  };

  module.exports = {Test_Client};

}).call(this);
