// Generated by CoffeeScript 2.7.0
(function() {
  //!/usr/bin/env coffee

  //  file: /src/test/index.coffee
  //  package: ws-rmi

  var client, examples, options, server;

  client = require('./client');

  server = require('./server');

  options = require('./options');

  examples = require('./examples');

  module.exports = {client, server, options, examples};

}).call(this);
