// Generated by CoffeeScript 2.7.0
(function() {
  // -*- coffee -*-

  //  file: /src/test/ipc_client.coffee
  //  package: ws-rmi

  var Test_Client, ipc_client;

  ({Test_Client} = require('./client'));

  ipc_client = new Test_Client('ipc');

  ipc_client.add_example('stack');

  module.exports = ipc_client;

}).call(this);
