// Generated by CoffeeScript 2.7.0
(function() {
  // -*- coffee -*-

  //  file: /src/test/ipc_server.coffee
  //  package: ws-rmi

  var Test_Server, ipc_server;

  ({Test_Server} = require('./server'));

  ipc_server = new Test_Server('ipc');

  ipc_server.add_example('stack');

  module.exports = ipc_server;

}).call(this);
