// Generated by CoffeeScript 2.7.0
(function() {
  // -*- coffee -*-

  //  file: /src/test/remote_client.coffee
  //  package: ws-rmi

  var Test_Client, remote_client;

  ({Test_Client} = require('./client'));

  remote_client = new Test_Client('remote');

  remote_client.add_example('stack');

  if (typeof window !== "undefined" && window !== null) {
    window.client = remote_client;
  } else {
    module.exports = remote_client;
  }

}).call(this);
