// Generated by CoffeeScript 2.7.0
(function() {
  // -*- coffee -*-

  //  file: /src/test/server.coffee
  //  package: ws-rmi

  var RMI_Connection, RMI_Server, Test_Server, examples, options_choices,
    boundMethodCheck = function(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new Error('Bound instance method accessed before binding'); } };

  ({RMI_Server, RMI_Connection} = require('../lib'));

  options_choices = require('./options');

  examples = require('./examples');

  Test_Server = class Test_Server extends RMI_Server {
    constructor(type = 'ipc') {
      var options;
      options = options_choices[type];
      super({options});
      this.add_example = this.add_example.bind(this);
    }

    add_example(name = 'stack') {
      var spec;
      boundMethodCheck(this, Test_Server);
      spec = examples[name];
      return this.add_object({
        obj: new spec.Class(),
        method_names: spec.method_names
      });
    }

  };

  module.exports = {Test_Server};

}).call(this);
