// Generated by CoffeeScript 2.4.1
(function() {
  // file: index.js
  // package: ws-rmi
  var lib;

  lib = require('./lib/index');

  exports.Connection = lib.Connection;

  exports.Object = lib.Object;

  exports.Stub = lib.Stub;

  exports.Server = lib.Server;

  exports.Client = lib.Client;

}).call(this);
