// Generated by CoffeeScript 2.7.0
(function() {
  // -*- coffee -*-

  //  file: /src/test/ipc_proxy/client.coffee
  //  package: ws-rmi

  var RMI_Client, client, options, stack;

  ({RMI_Client} = require('../../lib'));

  options = require('../options');

  ({stack} = require('../examples'));

  client = new RMI_Client({
    options: options.ipc_proxy
  });

  client.add_object({
    obj: new stack.Class(),
    method_names: stack.method_names
  });

  module.exports = client;

}).call(this);

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiY2xpZW50LmpzIiwic291cmNlUm9vdCI6Ii4uLy4uLy4uLyIsInNvdXJjZXMiOlsic3JjL3Rlc3QvaXBjX3Byb3h5L2NsaWVudC5jb2ZmZWUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUlDO0VBQUE7Ozs7O0FBQUEsTUFBQSxVQUFBLEVBQUEsTUFBQSxFQUFBLE9BQUEsRUFBQTs7RUFFRCxDQUFBLENBQUUsVUFBRixDQUFBLEdBQWlCLE9BQUEsQ0FBUSxXQUFSLENBQWpCOztFQUNBLE9BQUEsR0FBVSxPQUFBLENBQVEsWUFBUjs7RUFDVixDQUFBLENBQUUsS0FBRixDQUFBLEdBQVksT0FBQSxDQUFRLGFBQVIsQ0FBWjs7RUFFQSxNQUFBLEdBQVMsSUFBSSxVQUFKLENBQWU7SUFBRSxPQUFBLEVBQVMsT0FBTyxDQUFDO0VBQW5CLENBQWY7O0VBQ1QsTUFBTSxDQUFDLFVBQVAsQ0FBa0I7SUFDaEIsR0FBQSxFQUFLLElBQUksS0FBSyxDQUFDLEtBQVYsQ0FBQSxDQURXO0lBRWhCLFlBQUEsRUFBYyxLQUFLLENBQUM7RUFGSixDQUFsQjs7RUFLQSxNQUFNLENBQUMsT0FBUCxHQUFpQjtBQVpoQiIsInNvdXJjZXNDb250ZW50IjpbIiMgLSotIGNvZmZlZSAtKi1cbiNcbiMgIGZpbGU6IC9zcmMvdGVzdC9pcGNfcHJveHkvY2xpZW50LmNvZmZlZVxuIyAgcGFja2FnZTogd3Mtcm1pXG4jXG5cbnsgUk1JX0NsaWVudCB9ID0gcmVxdWlyZSgnLi4vLi4vbGliJylcbm9wdGlvbnMgPSByZXF1aXJlKCcuLi9vcHRpb25zJylcbnsgc3RhY2sgfSA9IHJlcXVpcmUoJy4uL2V4YW1wbGVzJylcblxuY2xpZW50ID0gbmV3IFJNSV9DbGllbnQoeyBvcHRpb25zOiBvcHRpb25zLmlwY19wcm94eSB9KVxuY2xpZW50LmFkZF9vYmplY3Qoe1xuICBvYmo6IG5ldyBzdGFjay5DbGFzcygpXG4gIG1ldGhvZF9uYW1lczogc3RhY2subWV0aG9kX25hbWVzXG4gIH0pXG5cbm1vZHVsZS5leHBvcnRzID0gY2xpZW50XG4iXX0=
//# sourceURL=/usr/local/server/git/github/ws-rmi/src/test/ipc_proxy/client.coffee