// Generated by CoffeeScript 2.7.0
(function() {
  // -*- coffee -*-

  //  file: /src/test/ipc_proxy/proxy.coffee
  //  package: ws-rmi

  var RMI_Proxy, options, proxy;

  ({RMI_Proxy} = require('../../lib'));

  options = require('../options');

  proxy = new RMI_Proxy({
    options: options.ipc_proxy
  });

  proxy.add_backend({
    options: options.ipc_server
  });

  module.exports = proxy;

}).call(this);

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicHJveHkuanMiLCJzb3VyY2VSb290IjoiLi4vLi4vLi4vIiwic291cmNlcyI6WyJzcmMvdGVzdC9pcGNfcHJveHkvcHJveHkuY29mZmVlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFJQztFQUFBOzs7OztBQUFBLE1BQUEsU0FBQSxFQUFBLE9BQUEsRUFBQTs7RUFFRCxDQUFBLENBQUUsU0FBRixDQUFBLEdBQWdCLE9BQUEsQ0FBUSxXQUFSLENBQWhCOztFQUNBLE9BQUEsR0FBVSxPQUFBLENBQVEsWUFBUjs7RUFFVixLQUFBLEdBQVEsSUFBSSxTQUFKLENBQWM7SUFBRSxPQUFBLEVBQVMsT0FBTyxDQUFDO0VBQW5CLENBQWQ7O0VBQ1IsS0FBSyxDQUFDLFdBQU4sQ0FBa0I7SUFBRSxPQUFBLEVBQVMsT0FBTyxDQUFDO0VBQW5CLENBQWxCOztFQUVBLE1BQU0sQ0FBQyxPQUFQLEdBQWlCO0FBUmhCIiwic291cmNlc0NvbnRlbnQiOlsiIyAtKi0gY29mZmVlIC0qLVxuI1xuIyAgZmlsZTogL3NyYy90ZXN0L2lwY19wcm94eS9wcm94eS5jb2ZmZWVcbiMgIHBhY2thZ2U6IHdzLXJtaVxuI1xuXG57IFJNSV9Qcm94eSB9ID0gcmVxdWlyZSgnLi4vLi4vbGliJylcbm9wdGlvbnMgPSByZXF1aXJlKCcuLi9vcHRpb25zJylcblxucHJveHkgPSBuZXcgUk1JX1Byb3h5KHsgb3B0aW9uczogb3B0aW9ucy5pcGNfcHJveHkgfSlcbnByb3h5LmFkZF9iYWNrZW5kKHsgb3B0aW9uczogb3B0aW9ucy5pcGNfc2VydmVyIH0pXG5cbm1vZHVsZS5leHBvcnRzID0gcHJveHlcbiJdfQ==
//# sourceURL=/usr/local/server/git/github/ws-rmi/src/test/ipc_proxy/proxy.coffee