// Generated by CoffeeScript 2.7.0
(function() {
  // -*- coffee -*-

  //  file: /src/test/ipc_proxy/server.coffee
  //  package: ws-rmi

  var RMI_Server, options, server, stack;

  ({RMI_Server} = require('../../lib'));

  options = require('../options');

  ({stack} = require('../examples'));

  server = new RMI_Server({
    options: options.ipc_server
  });

  server.add_object({
    obj: new stack.Class(),
    method_names: stack.method_names
  });

  module.exports = server;

}).call(this);

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic2VydmVyLmpzIiwic291cmNlUm9vdCI6Ii4uLy4uLy4uLyIsInNvdXJjZXMiOlsic3JjL3Rlc3QvaXBjX3Byb3h5L3NlcnZlci5jb2ZmZWUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUlDO0VBQUE7Ozs7O0FBQUEsTUFBQSxVQUFBLEVBQUEsT0FBQSxFQUFBLE1BQUEsRUFBQTs7RUFFRCxDQUFBLENBQUUsVUFBRixDQUFBLEdBQWlCLE9BQUEsQ0FBUSxXQUFSLENBQWpCOztFQUNBLE9BQUEsR0FBVSxPQUFBLENBQVEsWUFBUjs7RUFDVixDQUFBLENBQUUsS0FBRixDQUFBLEdBQVksT0FBQSxDQUFRLGFBQVIsQ0FBWjs7RUFFQSxNQUFBLEdBQVMsSUFBSSxVQUFKLENBQWU7SUFBRSxPQUFBLEVBQVMsT0FBTyxDQUFDO0VBQW5CLENBQWY7O0VBQ1QsTUFBTSxDQUFDLFVBQVAsQ0FBa0I7SUFDaEIsR0FBQSxFQUFLLElBQUksS0FBSyxDQUFDLEtBQVYsQ0FBQSxDQURXO0lBRWhCLFlBQUEsRUFBYyxLQUFLLENBQUM7RUFGSixDQUFsQjs7RUFLQSxNQUFNLENBQUMsT0FBUCxHQUFpQjtBQVpoQiIsInNvdXJjZXNDb250ZW50IjpbIiMgLSotIGNvZmZlZSAtKi1cbiNcbiMgIGZpbGU6IC9zcmMvdGVzdC9pcGNfcHJveHkvc2VydmVyLmNvZmZlZVxuIyAgcGFja2FnZTogd3Mtcm1pXG4jXG5cbnsgUk1JX1NlcnZlciB9ID0gcmVxdWlyZSgnLi4vLi4vbGliJylcbm9wdGlvbnMgPSByZXF1aXJlKCcuLi9vcHRpb25zJylcbnsgc3RhY2sgfSA9IHJlcXVpcmUoJy4uL2V4YW1wbGVzJylcblxuc2VydmVyID0gbmV3IFJNSV9TZXJ2ZXIoeyBvcHRpb25zOiBvcHRpb25zLmlwY19zZXJ2ZXIgfSlcbnNlcnZlci5hZGRfb2JqZWN0KHtcbiAgb2JqOiBuZXcgc3RhY2suQ2xhc3MoKVxuICBtZXRob2RfbmFtZXM6IHN0YWNrLm1ldGhvZF9uYW1lc1xuICB9KVxuXG5tb2R1bGUuZXhwb3J0cyA9IHNlcnZlclxuIl19
//# sourceURL=/usr/local/server/git/github/ws-rmi/src/test/ipc_proxy/server.coffee