// Generated by CoffeeScript 2.7.0
(function() {
  // -*- coffee -*-

  //  file: /src/test/ipc/client.coffee
  //  package: ws-rmi

  var RMI_Client, client, options, spec;

  ({RMI_Client} = require('../../lib'));

  options = require('../options').ipc_server;

  spec = require('../examples').stack;

  client = new RMI_Client({options});

  client.add_object({
    obj: new spec.Class(),
    method_names: spec.method_names
  });

  module.exports = client;

}).call(this);

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiY2xpZW50LmpzIiwic291cmNlUm9vdCI6Ii4uLy4uLy4uLyIsInNvdXJjZXMiOlsic3JjL3Rlc3QvaXBjL2NsaWVudC5jb2ZmZWUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUlDO0VBQUE7Ozs7O0FBQUEsTUFBQSxVQUFBLEVBQUEsTUFBQSxFQUFBLE9BQUEsRUFBQTs7RUFFRCxDQUFBLENBQUUsVUFBRixDQUFBLEdBQWlCLE9BQUEsQ0FBUSxXQUFSLENBQWpCOztFQUNBLE9BQUEsR0FBVSxPQUFBLENBQVEsWUFBUixDQUFxQixDQUFDOztFQUNoQyxJQUFBLEdBQU8sT0FBQSxDQUFRLGFBQVIsQ0FBc0IsQ0FBQzs7RUFFOUIsTUFBQSxHQUFTLElBQUksVUFBSixDQUFlLENBQUUsT0FBRixDQUFmOztFQUNULE1BQU0sQ0FBQyxVQUFQLENBQWtCO0lBQ2hCLEdBQUEsRUFBSyxJQUFJLElBQUksQ0FBQyxLQUFULENBQUEsQ0FEVztJQUVoQixZQUFBLEVBQWMsSUFBSSxDQUFDO0VBRkgsQ0FBbEI7O0VBS0EsTUFBTSxDQUFDLE9BQVAsR0FBaUI7QUFaaEIiLCJzb3VyY2VzQ29udGVudCI6WyIjIC0qLSBjb2ZmZWUgLSotXG4jXG4jICBmaWxlOiAvc3JjL3Rlc3QvaXBjL2NsaWVudC5jb2ZmZWVcbiMgIHBhY2thZ2U6IHdzLXJtaVxuI1xuXG57IFJNSV9DbGllbnQgfSA9IHJlcXVpcmUoJy4uLy4uL2xpYicpXG5vcHRpb25zID0gcmVxdWlyZSgnLi4vb3B0aW9ucycpLmlwY19zZXJ2ZXJcbnNwZWMgPSByZXF1aXJlKCcuLi9leGFtcGxlcycpLnN0YWNrXG5cbmNsaWVudCA9IG5ldyBSTUlfQ2xpZW50KHsgb3B0aW9ucyB9KVxuY2xpZW50LmFkZF9vYmplY3Qoe1xuICBvYmo6IG5ldyBzcGVjLkNsYXNzKClcbiAgbWV0aG9kX25hbWVzOiBzcGVjLm1ldGhvZF9uYW1lc1xuICB9KVxuXG5tb2R1bGUuZXhwb3J0cyA9IGNsaWVudFxuIl19
//# sourceURL=/usr/local/server/git/github/ws-rmi/src/test/ipc/client.coffee