// Generated by CoffeeScript 2.7.0
(function() {
  //!/usr/bin/env coffee

  // file: /src/test/ipc/index.coffee
  // package: ws-rmi

  var client, server;

  client = require('./client');

  server = require('./server');

  module.exports = {client, server};

}).call(this);

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguanMiLCJzb3VyY2VSb290IjoiLi4vLi4vLi4vIiwic291cmNlcyI6WyJzcmMvdGVzdC9pcGMvaW5kZXguY29mZmVlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFJQztFQUFBOzs7OztBQUFBLE1BQUEsTUFBQSxFQUFBOztFQUdELE1BQUEsR0FBUyxPQUFBLENBQVEsVUFBUjs7RUFDVCxNQUFBLEdBQVMsT0FBQSxDQUFRLFVBQVI7O0VBRVQsTUFBTSxDQUFDLE9BQVAsR0FBaUIsQ0FDZixNQURlLEVBRWYsTUFGZTtBQU5oQiIsInNvdXJjZXNDb250ZW50IjpbIiMhL3Vzci9iaW4vZW52IGNvZmZlZVxuI1xuIyBmaWxlOiAvc3JjL3Rlc3QvaXBjL2luZGV4LmNvZmZlZVxuIyBwYWNrYWdlOiB3cy1ybWlcbiNcblxuXG5jbGllbnQgPSByZXF1aXJlKCcuL2NsaWVudCcpXG5zZXJ2ZXIgPSByZXF1aXJlKCcuL3NlcnZlcicpXG5cbm1vZHVsZS5leHBvcnRzID0ge1xuICBjbGllbnRcbiAgc2VydmVyXG59XG4iXX0=
//# sourceURL=/usr/local/server/git/github/ws-rmi/src/test/ipc/index.coffee