// Generated by CoffeeScript 2.7.0
(function() {
  // -*- coffee -*-

  //  file: /src/test/ipc/server.coffee
  //  package: ws-rmi

  var RMI_Server, options, server, spec;

  ({RMI_Server} = require('../../lib'));

  options = require('../options').ipc_server;

  spec = require('../examples').stack;

  server = new RMI_Server({options});

  server.add_object({
    obj: new spec.Class(),
    method_names: spec.method_names
  });

  module.exports = server;

}).call(this);

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic2VydmVyLmpzIiwic291cmNlUm9vdCI6Ii4uLy4uLy4uLyIsInNvdXJjZXMiOlsic3JjL3Rlc3QvaXBjL3NlcnZlci5jb2ZmZWUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUlDO0VBQUE7Ozs7O0FBQUEsTUFBQSxVQUFBLEVBQUEsT0FBQSxFQUFBLE1BQUEsRUFBQTs7RUFFRCxDQUFBLENBQUUsVUFBRixDQUFBLEdBQWlCLE9BQUEsQ0FBUSxXQUFSLENBQWpCOztFQUNBLE9BQUEsR0FBVSxPQUFBLENBQVEsWUFBUixDQUFxQixDQUFDOztFQUNoQyxJQUFBLEdBQU8sT0FBQSxDQUFRLGFBQVIsQ0FBc0IsQ0FBQzs7RUFFOUIsTUFBQSxHQUFTLElBQUksVUFBSixDQUFlLENBQUUsT0FBRixDQUFmOztFQUNULE1BQU0sQ0FBQyxVQUFQLENBQWtCO0lBQ2hCLEdBQUEsRUFBSyxJQUFJLElBQUksQ0FBQyxLQUFULENBQUEsQ0FEVztJQUVoQixZQUFBLEVBQWMsSUFBSSxDQUFDO0VBRkgsQ0FBbEI7O0VBS0EsTUFBTSxDQUFDLE9BQVAsR0FBaUI7QUFaaEIiLCJzb3VyY2VzQ29udGVudCI6WyIjIC0qLSBjb2ZmZWUgLSotXG4jXG4jICBmaWxlOiAvc3JjL3Rlc3QvaXBjL3NlcnZlci5jb2ZmZWVcbiMgIHBhY2thZ2U6IHdzLXJtaVxuI1xuXG57IFJNSV9TZXJ2ZXIgfSA9IHJlcXVpcmUoJy4uLy4uL2xpYicpXG5vcHRpb25zID0gcmVxdWlyZSgnLi4vb3B0aW9ucycpLmlwY19zZXJ2ZXJcbnNwZWMgPSByZXF1aXJlKCcuLi9leGFtcGxlcycpLnN0YWNrXG5cbnNlcnZlciA9IG5ldyBSTUlfU2VydmVyKHsgb3B0aW9ucyB9KVxuc2VydmVyLmFkZF9vYmplY3Qoe1xuICBvYmo6IG5ldyBzcGVjLkNsYXNzKClcbiAgbWV0aG9kX25hbWVzOiBzcGVjLm1ldGhvZF9uYW1lc1xuICB9KVxuXG5tb2R1bGUuZXhwb3J0cyA9IHNlcnZlclxuIl19
//# sourceURL=/usr/local/server/git/github/ws-rmi/src/test/ipc/server.coffee