// Generated by CoffeeScript 2.7.0
(function() {
  // -*- coffee -*-

  //  file: /src/lib/index.coffee
  //  package: ws-rmi

  var RMI_Client, RMI_Connection, RMI_Object, RMI_Object_Registry, RMI_Server, RMI_Stub, RMI_Stub_Registry;

  ({RMI_Client} = require('./rmi_client'));

  ({RMI_Server} = require('./rmi_server'));

  ({RMI_Connection} = require('./rmi_connection'));

  ({RMI_Object, RMI_Stub} = require('./rmi_object'));

  ({RMI_Object_Registry, RMI_Stub_Registry} = require('./rmi_registry'));

  module.exports = {RMI_Client, RMI_Server, RMI_Connection, RMI_Object, RMI_Stub, RMI_Object_Registry, RMI_Stub_Registry};

}).call(this);
