// Generated by CoffeeScript 2.7.0
(function() {
  //!/usr/bin/env coffee

  //  file: /src/lib/rmi_object.coffee

  var Logger, RMI_Client, RMI_Connection, RMI_Object, RMI_Object_Registry, RMI_Registry_Admin, RMI_Stub, RMI_Stub_Registry, WebSocket, random_id,
    indexOf = [].indexOf;

  ({random_id, Logger} = require('armazilla-util'));

  ({RMI_Object, RMI_Stub} = require('./rmi_object'));

  WebSocket = (typeof window !== "undefined" && window !== null) && window.WebSocket || require('ws');

  //----------------------------------------------------------------------
  // RMI_Object
  // RMI_Object wraps a regular coffeescript class instance object,
  // exposing only those methods explicitly intended for RMI.

  RMI_Object = class RMI_Object {
    constructor({obj, name, method_names, options}) {
      var i, len, ref;
      this.get_stub_spec = this.get_stub_spec.bind(this);
      // Method invoke() is called by connection.recv_request() it executes
      // the appropriate method and returns a promise.

      this.invoke = this.invoke.bind(this);
      this.id = random_id(this);
      this.obj = obj;
      this.name = name || this.id;
      this.method_names = method_names || [];
      this.options = options || {};
      this.logger = new Logger({
        obj: this,
        threshold: 0,
        options: options
      });
      this.log = this.logger.log;
      ref = this.method_names;
      for (i = 0, len = ref.length; i < len; i++) {
        name = ref[i];
        this[name] = ((method_name) => {
          return (...args) => {
            return this.invoke({method_name, args});
          };
        })(name);
      }
    }

    get_stub_spec() {
      return {
        obj_id: this.id,
        name: this.name,
        method_names: this.method_names
      };
    }

    invoke({method_name, args}) {
      var obj_id;
      obj_id = this.id;
      this.log({obj_id, method_name, args});
      return new Promise((resolve, reject) => {
        var err, res;
        try {
          // call the method of the underlying object
          //res = @obj[method_name].apply(@obj, args)
          res = this.obj[method_name](...args);
          return resolve(res);
        } catch (error1) {
          err = error1;
          this.logger.log("rmi failed", {method_name, args});
          return reject(err.msg);
        }
      });
    }

  };

  //-----------------------------------------------------------------------
  // RMI_Stub
  RMI_Stub = class RMI_Stub {
    constructor({obj_id, name, method_names, send_request, options}) {
      var i, len, ref;
      // Method invoke() implements local stub methods by calling
      // RMI_Connection.send_request() which returns a Promise.

      this.invoke = this.invoke.bind(this);
      this.id = random_id(this);
      this.obj_id = obj_id;
      this.name = name || this.obj_id;
      this.method_names = method_names || [];
      this.send_request = send_request || null;
      this.options = options || {};
      this.logger = new Logger({
        obj: this,
        threshold: 0,
        options: this.options
      });
      this.log = this.logger.log;
      ref = this.method_names;
      for (i = 0, len = ref.length; i < len; i++) {
        name = ref[i];
        this[name] = ((method_name) => {
          return function(...args) {
            return this.invoke({method_name, args});
          };
        })(name);
      }
    }

    invoke({method_name, args}) {
      var obj_id, request;
      obj_id = this.obj_id;
      request = {obj_id, method_name, args};
      this.log(request);
      return new Promise((resolve, reject) => {
        var err, res;
        try {
          res = this.send_request(request);
          return resolve(res);
        } catch (error1) {
          err = error1;
          this.log("rmi failed", request);
          return reject(err.msg);
        }
      });
    }

  };

  //----------------------------------------------------------------------

    //!/usr/bin/env coffee

  //  file: /src/lib/rmi_registry.coffee

    //-----------------------------------------------------------------------
  // RMI_Object_Registry

  RMI_Registry_Admin = class RMI_Registry_Admin { // extends RMI_Object
    constructor(registry) {
      this.get_stub_spec = this.get_stub_spec.bind(this);
      // Method get_stub_specs() is a server side built-in remote method.
      // It is invoked by method invoke_stubs() on the client side. (see
      // below)

      this.get_stub_specs = this.get_stub_specs.bind(this);
      this.registry = registry;
      this.id = 'admin';
      this.name = 'admin';
      this.method_names = ['get_stub_specs'];
      this.logger = new Logger({
        obj: this,
        threshold: 0,
        options: this.options
      });
      this.log = this.logger.log;
    }

    get_stub_spec() {
      return {
        obj_id: this.id,
        name: this.name,
        method_names: this.method_names
      };
    }

    get_stub_specs() {
      var error, excluded, id, k, obj, specs, v;
      try {
        specs = (function() {
          var ref, results;
          ref = this.registry.objects;
          results = [];
          for (id in ref) {
            obj = ref[id];
            results.push(obj.get_stub_spec());
          }
          return results;
        }).call(this);
        excluded = (function() {
          var ref, results;
          ref = this.registry.exclude_ids;
          results = [];
          for (k in ref) {
            v = ref[k];
            results.push(k);
          }
          return results;
        }).call(this);
        specs = specs.filter(function(obj) {
          var ref;
          return ref = obj.id, indexOf.call(excluded, ref) < 0;
        });
        return specs;
      } catch (error1) {
        error = error1;
        return this.log(specs, error.msg);
      }
    }

  };

  //-----------------------------------------------------------------------
  // RMI_Object_Registry

  RMI_Object_Registry = class RMI_Object_Registry {
    constructor({owner, connection, options}) {
      this.set_owner = this.set_owner.bind(this);
      this.update = this.update.bind(this);
      this.set_connection = this.set_connection.bind(this);
      this.exclude = this.exclude.bind(this);
      this.include = this.include.bind(this);
      this.add_admin = this.add_admin.bind(this);
      // Method add_object(obj, method_names)
      // obj: a coffeescript object
      // method_names: a list of methods to expose

      this.add_object = this.add_object.bind(this);
      // why?
      // rmi_obj.connection = @connection

      // Method get_object(id)
      // id: the id of the object to get

      this.get_object = this.get_object.bind(this);
      // Method del_object(id)
      // id: the id of the object to delete

      this.del_object = this.del_object.bind(this);
      // Method handle_request(request)
      // request: a request JSON string

      this.handle_request = this.handle_request.bind(this);
      this.id = random_id(this);
      this.objects = {};
      this.exclude_ids = {};
      this.set_owner(owner);
      this.set_connection(connection) || null;
      this.options = options || {};
      this.logger = new Logger({
        obj: this,
        threshold: 0,
        options: this.options
      });
      this.log = this.logger.log;
      this.add_admin();
    }

    set_owner(owner) {
      return this.owner = owner;
    }

    update() {
      var id, method_names, obj, ref, results, spec;
      this.objects = {};
      this.add_admin();
      ref = this.owner.objects;
      results = [];
      for (id in ref) {
        spec = ref[id];
        ({obj, method_names} = spec);
        results.push(this.add_object({obj, method_names}));
      }
      return results;
    }

    set_connection(connection) {
      return this.connection = connection || null;
    }

    exclude(obj) {
      return this.exclude_ids[obj.id];
    }

    include(obj) {
      return delete this.exclude_ids[obj.id];
    }

    add_admin() {
      this.admin = new RMI_Registry_Admin(this);
      this.log(this.admin.get_stub_spec());
      this.objects[this.admin.id] = this.admin;
      return this.exclude_ids[this.admin.id] = true;
    }

    add_object({obj, name, method_names}) {
      var id, options, rmi_obj;
      name = name || obj.name;
      options = this.options;
      rmi_obj = new RMI_Object({obj, name, method_names, options});
      id = rmi_obj.id;
      this.log({id, name, method_names});
      return this.objects[rmi_obj.id] = rmi_obj;
    }

    get_object(obj_id) {
      return this.objects[obj_id];
    }

    del_object(obj_id) {
      if (indexOf.call(this.exclude, obj_id) < 0) {
        return delete this.objects[obj_id];
      }
    }

    handle_request({obj_id, method_name, args}) {
      var request;
      request = {obj_id, method_name, args};
      this.log(request);
      return new Promise(async(resolve, reject) => {
        var err, obj, result;
        try {
          obj = this.objects[obj_id];
          result = (await obj[method_name](...args));
          this.log({request, result});
          return resolve(result);
        } catch (error1) {
          err = error1;
          return reject(err);
        }
      });
    }

  };

  //-----------------------------------------------------------------------
  // RMI_Stub_Registry

  RMI_Stub_Registry = class RMI_Stub_Registry {
    constructor(connection1, options1 = {}) {
      // Method init_stubs(conn)
      // conn: an instance of RMI_Connection
      // Call get_stub_specs() on the server side of this connection,
      // then build the local stubs for the remote objects' methods.

      this.init = this.init.bind(this);
      this.add_stub = this.add_stub.bind(this);
      this.del_stub = this.del_stub.bind(this);
      this.get_stub = this.get_stub.bind(this);
      this.get_stubs_by_name = this.get_stubs_by_name.bind(this);
      this.connection = connection1;
      this.options = options1;
      this.id = random_id(this);
      this.stubs = {};
      this.logger = new Logger({
        obj: this,
        threshold: 0,
        options: this.options
      });
      this.log = this.logger.log;
    }

    async init() {
      var err, i, len, method_names, name, obj_id, request, results, specs;
      request = {
        obj_id: 'admin',
        method_name: 'get_stub_specs',
        args: []
      };
      try {
        specs = (await this.connection.send_request(request));
        this.log(specs);
        results = [];
        for (i = 0, len = specs.length; i < len; i++) {
          ({obj_id, name, method_names} = specs[i]);
          results.push(this.add_stub({obj_id, name, method_names}));
        }
        return results;
      } catch (error1) {
        err = error1;
        return this.log("failed.", err);
      }
    }

    add_stub({obj_id, name, method_names}) {
      var send_request;
      this.log({obj_id, name, method_names});
      send_request = this.connection.send_request;
      return this.stubs[obj_id] = new RMI_Stub({obj_id, name, method_names, send_request});
    }

    del_stub(obj_id) {
      return delete this.stubs[obj_id];
    }

    get_stub(obj_id) {
      return this.stubs[obj_id];
    }

    get_stubs_by_name(name) {
      var _, stub, stubs;
      stubs = (function() {
        var ref, results;
        ref = this.stubs;
        results = [];
        for (_ in ref) {
          stub = ref[_];
          results.push(stub);
        }
        return results;
      }).call(this);
      return stubs.filter(function(x) {
        return x.name === name;
      });
    }

  };

  //-----------------------------------------------------------------------

    // -*- coffee -*-

  //  file: /src/lib/rmi_connection_separate.coffee
  //  package: ws-rmi

    //----------------------------------------------------------------------
  RMI_Connection = class RMI_Connection {
    // RMI_Connection is basically just a wrapper around a socket and is
    // intendend to be applied on both ends of the websocket.  @owner is
    // the rmi_client or the rmi_server which established this end of the
    // websocket.

    // The idea here is that the connection, once established, is
    // symmetrical with both ends having the ability to request a remote
    // method invocation and to respond to such requests.

    // TODO: I have not settled the design as yet.  Previously the RMI's
    // were requested by a RMI_Client and responded to by a RMI_Server.
    // My current thinking is that that functionality might be better off
    // here.

    constructor(owner1, ws, options1) {
      //--------------------------------------------------------------------
      // Event handlers

      // TODO: is this event handled here or in client and server?  Seems
      // like by the time the connection object is constructed it's already
      // open.  Could it be closed and opened again?  I wouldn't think so
      // unless I implement that in the server and client code.  It'd have
      // to keep stale connection objects around and re-activate them when
      // connected again.

      this.on_Open = this.on_Open.bind(this);
      // @log("connection opened: ", id: @id)

      // This is the "main event".  It's what we've all been waiting for!
      this.on_Message = this.on_Message.bind(this);
      // TODO: perhaps somebody should be notified here ?-) Who wanted this
      // connection in the first place?  Do we have their contact info?

      this.on_Close = this.on_Close.bind(this);
      // TODO: think of something to do here.
      this.on_Error = this.on_Error.bind(this);
      //----------------------------------------------------------

      this.disconnect = this.disconnect.bind(this);
      this.init = this.init.bind(this);
      //--------------------------------------------------------------------
      // Generic messaging methods

      // JSON.stringify and send.  Returns a promise.
      this.send_message = this.send_message.bind(this);
      // JSON.parse and handle as appropriate.
      this.recv_message = this.recv_message.bind(this);
      //--------------------------------------------------------------------
      // Methods to Send and Receive RMI Requests

      // Method send_request()
      this.send_request = this.send_request.bind(this);
      // Method recv_request()
      this.recv_request = this.recv_request.bind(this);
      //--------------------------------------------------------------------
      //  Methods to Send and Receive RMI Responses

      // Method send_response()
      this.send_response = this.send_response.bind(this);
      // Method recv_resonse()
      this.recv_response = this.recv_response.bind(this);
      this.owner = owner1;
      this.ws = ws;
      this.options = options1;
      this.id = random_id('RMI_Connection');
      this.logger = new Logger(this, {
        threshold: 2,
        options: this.options
      });
      this.log = this.logger.log;
      this.waiter = null;
      this.registry = this.owner.registry;
      this.stub_registry = new RMI_Stub_Registry(this, this.options);
      // RMI's are given a unique number and the Promise's resolve() and
      // reject() functions are kept as callbacks to be executed when an
      // RMI response is received. Properties @rmi_cnt and @rmi_hash are
      // each written and read by methods send_request() and
      // recv_response().

      this.rmi_cnt = 0;
      this.rmi_hash = {};
      // Events are mapped to handler methods defined below.

      this.ws.onopen = this.on_Open;
      this.ws.onmessage = this.on_Message;
      this.ws.onclose = this.on_Close;
      this.ws.onerror = this.on_Error;
      true;
    }

    on_Open(evt) {}

    on_Message(evt) {
      //@log(evt.data)
      return this.recv_message(evt.data);
    }

    on_Close(evt) {
      this.log("peer disconnected.", evt.data);
      return this.owner.remove_connection(this.id);
    }

    on_Error(evt) {
      this.log(evt.data);
      if (this.waiter) {
        return clearInterval(this.waiter);
      }
    }

    disconnect() {
      return this.ws.close();
    }

    async init() {
      return (await this.stub_registry.init());
    }

    send_message({type, msg}) {
      var data, delay, error, max_tries, tries;
      this.log({type, msg});
      data = JSON.stringify({type, msg});
      try {
        // If the ws is connected then proceed as normal.

        if (this.ws.readyState === this.ws.OPEN) {
          return this.ws.send(data);
        // If not ready but we're still connecting, then check again
        // every ${delay} ms.

        } else if (this.ws.readyState === this.ws.CONNECTING) {
          delay = 100;
          max_tries = 30;
          tries = 0;
          return this.waiter = setInterval((() => {
            this.log(`waiting ${delay} ms...`);
            tries += 1;
            if (this.ws.readyState === this.ws.OPEN || tries >= max_tries) {
              clearInterval(this.waiter);
              return this.ws.send(data, delay);
            }
          }));
        } else {
          // The other possible states are CLOSED and CLOSING.  Either
          // of these is an error.

          throw new Error('ws.readyState not OPEN or CONNECTING');
        }
      } catch (error1) {
        error = error1;
        return this.log({data, error});
      }
    }

    recv_message(data) {
      var msg, type;
      ({type, msg} = JSON.parse(data));
      this.log({
        type: type,
        msg: msg
      });
      if (type === 'request') {
        return this.recv_request(msg);
      }
      if (type === 'response') {
        return this.recv_response(msg);
      } else {
        throw new Error(`recv_message(): invalid type ${type}`);
      }
    }

    send_request({obj_id, method_name, args}) {
      var msg, rmi_id;
      rmi_id = this.rmi_cnt++;
      msg = {rmi_id, obj_id, method_name, args};
      return new Promise((resolve, reject) => {
        var error;
        try {
          this.rmi_hash[rmi_id] = {msg, resolve, reject};
          this.log(msg);
          return this.send_message({
            type: 'request',
            msg: msg
          });
        } catch (error1) {
          error = error1;
          delete this.rmi_hash[rmi_id];
          return reject(`send_message():\n  ${error.msg}`);
        }
      });
    }

    async recv_request({rmi_id, obj_id, method_name, args}) {
      var err, error, msg, result;
      msg = {rmi_id, obj_id, method_name, args};
      this.log(msg);
      try {
        result = (await this.registry.handle_request({obj_id, method_name, args}));
        error = null;
        return this.send_response({rmi_id, result, error});
      } catch (error1) {
        err = error1;
        result = null;
        return this.send_response({rmi_id, result, error});
      }
    }

    send_response({rmi_id, result, error}) {
      var response;
      response = {rmi_id, result, error};
      this.log(response);
      return new Promise((resolve, reject) => {
        try {
          return this.send_message({
            type: 'response',
            msg: response
          });
        } catch (error1) {
          error = error1;
          this.log("Error in send_response():", {
            msg: resonse
          });
          return reject({rmi_id, result, error});
        }
      });
    }

    recv_response({rmi_id, result, error}) {
      var request, response;
      response = {rmi_id, result, error};
      this.log(response);
      request = this.rmi_hash[rmi_id];
      delete this.rmi_hash[rmi_id];
      try {
        if (result) {
          return request.resolve(result);
        } else {
          return request.reject({request, error});
        }
      } catch (error1) {
        error = error1;
        return request.reject({request, error});
      }
    }

  };

  //----------------------------------------------------------------------

    // -*- coffee -*-

  //  file: /src/client/rmi_client.coffee
  //  package: ws-rmi

  RMI_Client = class RMI_Client {
    // Connnection should be a sub-class of RMI_Connection in order to
    // create and register desired RMI_Objects at construction.

    constructor({objects, options, Socket, Connection}) {
      var ref, ref1, ref2, ref3, ref4;
      this.remove_connection = this.remove_connection.bind(this);
      this.add_object = this.add_object.bind(this);
      this.update_registry = this.update_registry.bind(this);
      //--------------------------------------------------------------------
      // connect() method

      this.connect = this.connect.bind(this);
      //--------------------------------------------------------------------
      // disconnect() method

      this.disconnect = this.disconnect.bind(this);
      this.id = random_id(this);
      this.objects = objects || {};
      this.options = options || {};
      this.Socket = Socket || WebSocket;
      this.Connection = Connection || RMI_Connection;
      this.registry = new RMI_Object_Registry({
        owner: this,
        options: this.options
      });
      this.logger = new Logger(this, {
        threshold: 2,
        options: options
      });
      this.log = this.logger.log;
      this.protocol = ((ref = this.options) != null ? ref.protocol : void 0) || 'ws+unix';
      if (this.protocol === 'ws+unix') {
        this.path = ((ref1 = this.options) != null ? ref1.path : void 0) || '/tmp/ipc_rmi';
        this.url = `ws+unix://${this.path}`;
      } else {
        this.host = ((ref2 = this.options) != null ? ref2.host : void 0) || localhost;
        this.port = ((ref3 = this.options) != null ? ref3.port : void 0) || 8007;
        this.path = ((ref4 = this.options) != null ? ref4.path : void 0) || '';
        this.url = `${this.protocol}://${this.host}:${this.port}/${this.path}`;
      }
      this.connection = null;
    }

    remove_connection() {
      return this.connection = null;
    }

    add_object({obj, method_names}) {
      return this.objects[obj.id] = {obj, method_names};
    }

    update_registry() {
      return this.registry.update();
    }

    connect(url) {
      this.log("RMI_Client.connect():", {
        id: this.id
      });
      return new Promise(async(resolve, reject) => {
        var error, msg;
        try {
          if (url) {
            this.url = url;
          }
          // Note: This is screwed up !!!
          // new WebSocket(@url) connects automatically but ws.onOpen
          // cannot be set until AFTER the ws object is constructed!
          // So the 'open' event can be emitted BEFORE the handler is set!
          // See note below ...

          this.ws = new this.Socket(this.url);
          // Note: @ws exists but is not necessarily ready yet.  This
          // issue is addressed in the RMI_Connection.send_message()
          // method (q.v.)

          this.connection = new this.Connection(this, this.ws, this.options);
          await this.connection.init();
          return resolve(this.connection);
        } catch (error1) {
          error = error1;
          msg = "\nRMI_Client: connect failed.\n";
          msg += error.toString() + '\n';
          msg += error.stack.split('\n').filter(function(x) {
            return /ws-rmi/.test(x);
          }).join('\n');
          return this.log(msg);
        }
      });
    }

    disconnect() {
      if (this.log_level > 0) {
        this.log("disconnecting:", {
          id: this.id
        });
      }
      return this.ws.close();
    }

  };

  module.exports = {RMI_Object, RMI_Stub, RMI_Object_Registry, RMI_Stub_Registry, RMI_Connection, RMI_Client};

}).call(this);
