// Generated by CoffeeScript 2.7.0
(function() {
  //!/usr/bin/env coffee

  //  file: /src/lib/rmi_registry.coffee

  var Logger, RMI_Object, RMI_Object_Registry, RMI_Registry_Admin, RMI_Stub, RMI_Stub_Registry, random_id,
    indexOf = [].indexOf;

  ({random_id, Logger} = require('armazilla-util'));

  ({RMI_Object, RMI_Stub} = require('./rmi_object'));

  //-----------------------------------------------------------------------
  // RMI_Object_Registry

  RMI_Registry_Admin = class RMI_Registry_Admin { // extends RMI_Object
    constructor(registry) {
      this.get_stub_spec = this.get_stub_spec.bind(this);
      // Method get_stub_specs() is a server side built-in remote method.
      // It is invoked by method invoke_stubs() on the client side. (see
      // below)

      this.get_stub_specs = this.get_stub_specs.bind(this);
      this.registry = registry;
      this.id = 'admin';
      this.name = 'admin';
      this.method_names = ['get_stub_specs'];
      this.logger = new Logger({
        obj: this,
        threshold: 0,
        options: this.options
      });
      this.log = this.logger.log;
    }

    get_stub_spec() {
      return {
        obj_id: this.id,
        name: this.name,
        method_names: this.method_names
      };
    }

    get_stub_specs() {
      var error, excluded, id, k, obj, specs, v;
      try {
        specs = (function() {
          var ref, results;
          ref = this.registry.objects;
          results = [];
          for (id in ref) {
            obj = ref[id];
            results.push(obj.get_stub_spec());
          }
          return results;
        }).call(this);
        excluded = (function() {
          var ref, results;
          ref = this.registry.exclude_ids;
          results = [];
          for (k in ref) {
            v = ref[k];
            results.push(k);
          }
          return results;
        }).call(this);
        specs = specs.filter(function(obj) {
          var ref;
          return ref = obj.id, indexOf.call(excluded, ref) < 0;
        });
        return specs;
      } catch (error1) {
        error = error1;
        return this.log(specs, error.msg);
      }
    }

  };

  //-----------------------------------------------------------------------
  // RMI_Object_Registry

  RMI_Object_Registry = class RMI_Object_Registry {
    constructor({owner, connection, options}) {
      this.set_owner = this.set_owner.bind(this);
      this.update = this.update.bind(this);
      this.set_connection = this.set_connection.bind(this);
      this.exclude = this.exclude.bind(this);
      this.include = this.include.bind(this);
      this.add_admin = this.add_admin.bind(this);
      // Method add_object(obj, method_names)
      // obj: a coffeescript object
      // method_names: a list of methods to expose

      this.add_object = this.add_object.bind(this);
      // why?
      // rmi_obj.connection = @connection

      // Method get_object(id)
      // id: the id of the object to get

      this.get_object = this.get_object.bind(this);
      // Method del_object(id)
      // id: the id of the object to delete

      this.del_object = this.del_object.bind(this);
      // Method handle_request(request)
      // request: a request JSON string

      this.handle_request = this.handle_request.bind(this);
      this.id = random_id(this);
      this.objects = {};
      this.exclude_ids = {};
      this.set_owner(owner);
      this.set_connection(connection) || null;
      this.options = options || {};
      this.logger = new Logger({
        obj: this,
        threshold: 0,
        options: this.options
      });
      this.log = this.logger.log;
      this.add_admin();
    }

    set_owner(owner) {
      return this.owner = owner;
    }

    update() {
      var id, method_names, obj, ref, results, spec;
      this.objects = {};
      this.add_admin();
      ref = this.owner.objects;
      results = [];
      for (id in ref) {
        spec = ref[id];
        ({obj, method_names} = spec);
        results.push(this.add_object({obj, method_names}));
      }
      return results;
    }

    set_connection(connection) {
      return this.connection = connection || null;
    }

    exclude(obj) {
      return this.exclude_ids[obj.id];
    }

    include(obj) {
      return delete this.exclude_ids[obj.id];
    }

    add_admin() {
      this.admin = new RMI_Registry_Admin(this);
      this.log(this.admin.get_stub_spec());
      this.objects[this.admin.id] = this.admin;
      return this.exclude_ids[this.admin.id] = true;
    }

    add_object({obj, name, method_names}) {
      var id, options, rmi_obj;
      name = name || obj.name;
      options = this.options;
      rmi_obj = new RMI_Object({obj, name, method_names, options});
      id = rmi_obj.id;
      this.log({id, name, method_names});
      return this.objects[rmi_obj.id] = rmi_obj;
    }

    get_object(obj_id) {
      return this.objects[obj_id];
    }

    del_object(obj_id) {
      if (indexOf.call(this.exclude, obj_id) < 0) {
        return delete this.objects[obj_id];
      }
    }

    handle_request({obj_id, method_name, args}) {
      var request;
      request = {obj_id, method_name, args};
      this.log(request);
      return new Promise(async(resolve, reject) => {
        var err, obj, result;
        try {
          obj = this.objects[obj_id];
          result = (await obj[method_name](...args));
          this.log({request, result});
          return resolve(result);
        } catch (error1) {
          err = error1;
          return reject(err);
        }
      });
    }

  };

  //-----------------------------------------------------------------------
  // RMI_Stub_Registry

  RMI_Stub_Registry = class RMI_Stub_Registry {
    constructor(connection1, options1 = {}) {
      // Method init_stubs(conn)
      // conn: an instance of RMI_Connection
      // Call get_stub_specs() on the server side of this connection,
      // then build the local stubs for the remote objects' methods.

      this.init = this.init.bind(this);
      this.add_stub = this.add_stub.bind(this);
      this.del_stub = this.del_stub.bind(this);
      this.get_stub = this.get_stub.bind(this);
      this.get_stubs_by_name = this.get_stubs_by_name.bind(this);
      this.connection = connection1;
      this.options = options1;
      this.id = random_id(this);
      this.stubs = {};
      this.logger = new Logger({
        obj: this,
        threshold: 0,
        options: this.options
      });
      this.log = this.logger.log;
    }

    async init() {
      var err, i, len, method_names, name, obj_id, request, results, specs;
      request = {
        obj_id: 'admin',
        method_name: 'get_stub_specs',
        args: []
      };
      try {
        specs = (await this.connection.send_request(request));
        this.log(specs);
        results = [];
        for (i = 0, len = specs.length; i < len; i++) {
          ({obj_id, name, method_names} = specs[i]);
          results.push(this.add_stub({obj_id, name, method_names}));
        }
        return results;
      } catch (error1) {
        err = error1;
        return this.log("failed.", err);
      }
    }

    add_stub({obj_id, name, method_names}) {
      var send_request;
      this.log({obj_id, name, method_names});
      send_request = this.connection.send_request;
      return this.stubs[obj_id] = new RMI_Stub({obj_id, name, method_names, send_request});
    }

    del_stub(obj_id) {
      return delete this.stubs[obj_id];
    }

    get_stub(obj_id) {
      return this.stubs[obj_id];
    }

    get_stubs_by_name(name) {
      var _, stub, stubs;
      stubs = (function() {
        var ref, results;
        ref = this.stubs;
        results = [];
        for (_ in ref) {
          stub = ref[_];
          results.push(stub);
        }
        return results;
      }).call(this);
      return stubs.filter(function(x) {
        return x.name === name;
      });
    }

  };

  //-----------------------------------------------------------------------
  module.exports = {RMI_Object_Registry, RMI_Stub_Registry};

}).call(this);
