// Generated by CoffeeScript 2.7.0
(function() {
  //!/usr/bin/env coffee

  //  file: /src/lib/rmi_object.coffee

  var Logger, RMI_Object, RMI_Stub, random_id;

  ({random_id, Logger} = require('armazilla-util'));

  //----------------------------------------------------------------------
  // RMI_Object
  // RMI_Object wraps a regular coffeescript class instance object,
  // exposing only those methods explicitly intended for RMI.

  RMI_Object = class RMI_Object {
    constructor({obj, name, method_names, options}) {
      var i, len, ref;
      this.get_stub_spec = this.get_stub_spec.bind(this);
      // Method invoke() is called by connection.recv_request() it executes
      // the appropriate method and returns a promise.

      this.invoke = this.invoke.bind(this);
      this.id = random_id(this);
      this.obj = obj;
      this.name = name || this.id;
      this.method_names = method_names || [];
      this.options = options || {};
      this.logger = new Logger({
        obj: this,
        threshold: 0,
        options: options
      });
      this.log = this.logger.log;
      ref = this.method_names;
      for (i = 0, len = ref.length; i < len; i++) {
        name = ref[i];
        this[name] = ((method_name) => {
          return (...args) => {
            return this.invoke({method_name, args});
          };
        })(name);
      }
    }

    get_stub_spec() {
      return {
        obj_id: this.id,
        name: this.name,
        method_names: this.method_names
      };
    }

    invoke({method_name, args}) {
      var obj_id;
      obj_id = this.id;
      this.log({obj_id, method_name, args});
      return new Promise((resolve, reject) => {
        var err, res;
        try {
          // call the method of the underlying object
          //res = @obj[method_name].apply(@obj, args)
          res = this.obj[method_name](...args);
          return resolve(res);
        } catch (error) {
          err = error;
          this.logger.log("rmi failed", {method_name, args});
          return reject(err.msg);
        }
      });
    }

  };

  //-----------------------------------------------------------------------
  // RMI_Stub
  RMI_Stub = class RMI_Stub {
    constructor({obj_id, name, method_names, send_request, options}) {
      var i, len, ref;
      // Method invoke() implements local stub methods by calling
      // RMI_Connection.send_request() which returns a Promise.

      this.invoke = this.invoke.bind(this);
      this.id = random_id(this);
      this.obj_id = obj_id;
      this.name = name || this.obj_id;
      this.method_names = method_names || [];
      this.send_request = send_request || null;
      this.options = options || {};
      this.logger = new Logger({
        obj: this,
        threshold: 0,
        options: this.options
      });
      this.log = this.logger.log;
      ref = this.method_names;
      for (i = 0, len = ref.length; i < len; i++) {
        name = ref[i];
        this[name] = ((method_name) => {
          return function(...args) {
            return this.invoke({method_name, args});
          };
        })(name);
      }
    }

    invoke({method_name, args}) {
      var obj_id, request;
      obj_id = this.obj_id;
      request = {obj_id, method_name, args};
      this.log(request);
      return new Promise((resolve, reject) => {
        var err, res;
        try {
          res = this.send_request(request);
          return resolve(res);
        } catch (error) {
          err = error;
          this.log("rmi failed", request);
          return reject(err.msg);
        }
      });
    }

  };

  //----------------------------------------------------------------------
  module.exports = {RMI_Object, RMI_Stub};

}).call(this);
