// Generated by CoffeeScript 2.7.0
(function() {
  // -*- coffee -*-

  //  file: /src/client/rmi_client.coffee
  //  package: ws-rmi

  var Logger, RMI_Client, RMI_Connection, RMI_Object_Registry, WebSocket, random_id;

  WebSocket = (typeof window !== "undefined" && window !== null) && window.WebSocket || require('ws');

  ({random_id, Logger} = require('armazilla-util'));

  ({RMI_Connection} = require('./rmi_connection'));

  ({RMI_Object_Registry} = require('./rmi_registry'));

  RMI_Client = class RMI_Client {
    // Connnection should be a sub-class of RMI_Connection in order to
    // create and register desired RMI_Objects at construction.

    constructor({objects, options, Socket, Connection}) {
      var ref, ref1, ref2, ref3, ref4;
      this.remove_connection = this.remove_connection.bind(this);
      this.add_object = this.add_object.bind(this);
      this.update_registry = this.update_registry.bind(this);
      //--------------------------------------------------------------------
      // connect() method

      this.connect = this.connect.bind(this);
      //--------------------------------------------------------------------
      // disconnect() method

      this.disconnect = this.disconnect.bind(this);
      this.id = random_id(this);
      this.objects = objects || {};
      this.options = options || {};
      this.Socket = Socket || WebSocket;
      this.Connection = Connection || RMI_Connection;
      this.registry = new RMI_Object_Registry({
        owner: this,
        options: this.options
      });
      this.logger = new Logger(this, {
        threshold: 2,
        options: options
      });
      this.log = this.logger.log;
      this.protocol = ((ref = this.options) != null ? ref.protocol : void 0) || 'ws+unix';
      if (this.protocol === 'ws+unix') {
        this.path = ((ref1 = this.options) != null ? ref1.path : void 0) || '/tmp/ipc_rmi';
        this.url = `ws+unix://${this.path}`;
      } else {
        this.host = ((ref2 = this.options) != null ? ref2.host : void 0) || localhost;
        this.port = ((ref3 = this.options) != null ? ref3.port : void 0) || 8007;
        this.path = ((ref4 = this.options) != null ? ref4.path : void 0) || '';
        this.url = `${this.protocol}://${this.host}:${this.port}/${this.path}`;
      }
      this.connection = null;
    }

    remove_connection() {
      return this.connection = null;
    }

    add_object({obj, method_names}) {
      return this.objects[obj.id] = {obj, method_names};
    }

    update_registry() {
      return this.registry.update();
    }

    connect(url) {
      this.log("RMI_Client.connect():", {
        id: this.id
      });
      return new Promise(async(resolve, reject) => {
        var error, msg;
        try {
          if (url) {
            this.url = url;
          }
          // Note: This is screwed up !!!
          // new WebSocket(@url) connects automatically but ws.onOpen
          // cannot be set until AFTER the ws object is constructed!
          // So the 'open' event can be emitted BEFORE the handler is set!
          // See note below ...

          this.ws = new this.Socket(this.url);
          // Note: @ws exists but is not necessarily ready yet.  This
          // issue is addressed in the RMI_Connection.send_message()
          // method (q.v.)

          this.connection = new this.Connection(this, this.ws, this.options);
          await this.connection.init();
          return resolve(this.connection);
        } catch (error1) {
          error = error1;
          msg = "\nRMI_Client: connect failed.\n";
          msg += error.toString() + '\n';
          msg += error.stack.split('\n').filter(function(x) {
            return /ws-rmi/.test(x);
          }).join('\n');
          return this.log(msg);
        }
      });
    }

    disconnect() {
      if (this.log_level > 0) {
        this.log("disconnecting:", {
          id: this.id
        });
      }
      return this.ws.close();
    }

  };

  exports.RMI_Client = RMI_Client;

}).call(this);
