// Generated by CoffeeScript 2.7.0
(function() {
  // -*- coffee -*-

  //  file: /src/lib/rmi_connection_separate.coffee
  //  package: ws-rmi

  var Logger, RMI_Connection, RMI_Object_Registry, RMI_Stub_Registry, random_id;

  ({random_id, Logger} = require('armazilla-util'));

  ({RMI_Object_Registry, RMI_Stub_Registry} = require('./rmi_registry'));

  //----------------------------------------------------------------------
  RMI_Connection = class RMI_Connection {
    // RMI_Connection is basically just a wrapper around a socket and is
    // intendend to be applied on both ends of the websocket.  @owner is
    // the rmi_client or the rmi_server which established this end of the
    // websocket.

    // The idea here is that the connection, once established, is
    // symmetrical with both ends having the ability to request a remote
    // method invocation and to respond to such requests.

    // TODO: I have not settled the design as yet.  Previously the RMI's
    // were requested by a RMI_Client and responded to by a RMI_Server.
    // My current thinking is that that functionality might be better off
    // here.

    constructor(owner, ws, options) {
      //--------------------------------------------------------------------
      // Event handlers

      // TODO: is this event handled here or in client and server?  Seems
      // like by the time the connection object is constructed it's already
      // open.  Could it be closed and opened again?  I wouldn't think so
      // unless I implement that in the server and client code.  It'd have
      // to keep stale connection objects around and re-activate them when
      // connected again.

      this.on_Open = this.on_Open.bind(this);
      // @log("connection opened: ", id: @id)

      // This is the "main event".  It's what we've all been waiting for!
      this.on_Message = this.on_Message.bind(this);
      // TODO: perhaps somebody should be notified here ?-) Who wanted this
      // connection in the first place?  Do we have their contact info?

      this.on_Close = this.on_Close.bind(this);
      // TODO: think of something to do here.
      this.on_Error = this.on_Error.bind(this);
      //----------------------------------------------------------

      this.disconnect = this.disconnect.bind(this);
      this.init = this.init.bind(this);
      //--------------------------------------------------------------------
      // Generic messaging methods

      // JSON.stringify and send.  Returns a promise.
      this.send_message = this.send_message.bind(this);
      // JSON.parse and handle as appropriate.
      this.recv_message = this.recv_message.bind(this);
      //--------------------------------------------------------------------
      // Methods to Send and Receive RMI Requests

      // Method send_request()
      this.send_request = this.send_request.bind(this);
      // Method recv_request()
      this.recv_request = this.recv_request.bind(this);
      //--------------------------------------------------------------------
      //  Methods to Send and Receive RMI Responses

      // Method send_response()
      this.send_response = this.send_response.bind(this);
      // Method recv_resonse()
      this.recv_response = this.recv_response.bind(this);
      this.owner = owner;
      this.ws = ws;
      this.options = options;
      this.id = random_id('RMI_Connection');
      this.logger = new Logger(this, {
        threshold: 2,
        options: this.options
      });
      this.log = this.logger.log;
      this.waiter = null;
      this.registry = this.owner.registry;
      this.stub_registry = new RMI_Stub_Registry(this, this.options);
      // RMI's are given a unique number and the Promise's resolve() and
      // reject() functions are kept as callbacks to be executed when an
      // RMI response is received. Properties @rmi_cnt and @rmi_hash are
      // each written and read by methods send_request() and
      // recv_response().

      this.rmi_cnt = 0;
      this.rmi_hash = {};
      // Events are mapped to handler methods defined below.

      this.ws.onopen = this.on_Open;
      this.ws.onmessage = this.on_Message;
      this.ws.onclose = this.on_Close;
      this.ws.onerror = this.on_Error;
      true;
    }

    on_Open(evt) {}

    on_Message(evt) {
      //@log(evt.data)
      return this.recv_message(evt.data);
    }

    on_Close(evt) {
      this.log("peer disconnected.", evt.data);
      return this.owner.remove_connection(this.id);
    }

    on_Error(evt) {
      this.log(evt.data);
      if (this.waiter) {
        return clearInterval(this.waiter);
      }
    }

    disconnect() {
      return this.ws.close();
    }

    async init() {
      return (await this.stub_registry.init());
    }

    send_message({type, msg}) {
      var data, delay, error, max_tries, tries;
      this.log({type, msg});
      data = JSON.stringify({type, msg});
      try {
        // If the ws is connected then proceed as normal.

        if (this.ws.readyState === this.ws.OPEN) {
          return this.ws.send(data);
        // If not ready but we're still connecting, then check again
        // every ${delay} ms.

        } else if (this.ws.readyState === this.ws.CONNECTING) {
          delay = 100;
          max_tries = 30;
          tries = 0;
          return this.waiter = setInterval((() => {
            this.log(`waiting ${delay} ms...`);
            tries += 1;
            if (this.ws.readyState === this.ws.OPEN || tries >= max_tries) {
              clearInterval(this.waiter);
              return this.ws.send(data, delay);
            }
          }));
        } else {
          // The other possible states are CLOSED and CLOSING.  Either
          // of these is an error.

          throw new Error('ws.readyState not OPEN or CONNECTING');
        }
      } catch (error1) {
        error = error1;
        return this.log({data, error});
      }
    }

    recv_message(data) {
      var msg, type;
      ({type, msg} = JSON.parse(data));
      this.log({
        type: type,
        msg: msg
      });
      if (type === 'request') {
        return this.recv_request(msg);
      }
      if (type === 'response') {
        return this.recv_response(msg);
      } else {
        throw new Error(`recv_message(): invalid type ${type}`);
      }
    }

    send_request({obj_id, method_name, args}) {
      var msg, rmi_id;
      rmi_id = this.rmi_cnt++;
      msg = {rmi_id, obj_id, method_name, args};
      return new Promise((resolve, reject) => {
        var error;
        try {
          this.rmi_hash[rmi_id] = {msg, resolve, reject};
          this.log(msg);
          return this.send_message({
            type: 'request',
            msg: msg
          });
        } catch (error1) {
          error = error1;
          delete this.rmi_hash[rmi_id];
          return reject(`send_message():\n  ${error.msg}`);
        }
      });
    }

    async recv_request({rmi_id, obj_id, method_name, args}) {
      var err, error, msg, result;
      msg = {rmi_id, obj_id, method_name, args};
      this.log(msg);
      try {
        result = (await this.registry.handle_request({obj_id, method_name, args}));
        error = null;
        return this.send_response({rmi_id, result, error});
      } catch (error1) {
        err = error1;
        result = null;
        return this.send_response({rmi_id, result, error});
      }
    }

    send_response({rmi_id, result, error}) {
      var response;
      response = {rmi_id, result, error};
      this.log(response);
      return new Promise((resolve, reject) => {
        try {
          return this.send_message({
            type: 'response',
            msg: response
          });
        } catch (error1) {
          error = error1;
          this.log("Error in send_response():", {
            msg: resonse
          });
          return reject({rmi_id, result, error});
        }
      });
    }

    recv_response({rmi_id, result, error}) {
      var request, response;
      response = {rmi_id, result, error};
      this.log(response);
      request = this.rmi_hash[rmi_id];
      delete this.rmi_hash[rmi_id];
      try {
        if (result) {
          return request.resolve(result);
        } else {
          return request.reject({request, error});
        }
      } catch (error1) {
        error = error1;
        return request.reject({request, error});
      }
    }

  };

  //----------------------------------------------------------------------
  exports.RMI_Connection = RMI_Connection;

}).call(this);
