// Generated by CoffeeScript 2.7.0
(function() {
  //!/usr/bin/env coffee

  //  file: /src/lib/stacktrace.coffee
  //  package: armazilla-util

  var stacktrace;

  stacktrace = require('stacktrace-js');

  if (typeof window !== "undefined" && window !== null) {
    window.stacktrace = stacktrace;
  } else {
    module.exports = stacktrace;
  }

}).call(this);
