// Generated by CoffeeScript 2.7.0
(function() {
  //!/usr/bin/env coffee

  //  file: /src/test/examples/index.coffee
  //  package: ws-rmi

  var stack;

  stack = require('./stack');

  module.exports = {stack};

}).call(this);

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguanMiLCJzb3VyY2VSb290IjoiLi4vLi4vLi4vIiwic291cmNlcyI6WyJzcmMvdGVzdC9leGFtcGxlcy9pbmRleC5jb2ZmZWUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUlDO0VBQUE7Ozs7O0FBQUEsTUFBQTs7RUFFRCxLQUFBLEdBQVEsT0FBQSxDQUFRLFNBQVI7O0VBRVIsTUFBTSxDQUFDLE9BQVAsR0FBaUIsQ0FDZixLQURlO0FBSmhCIiwic291cmNlc0NvbnRlbnQiOlsiIyEvdXNyL2Jpbi9lbnYgY29mZmVlXG4jXG4jICBmaWxlOiAvc3JjL3Rlc3QvZXhhbXBsZXMvaW5kZXguY29mZmVlXG4jICBwYWNrYWdlOiB3cy1ybWlcbiNcblxuc3RhY2sgPSByZXF1aXJlKCcuL3N0YWNrJylcblxubW9kdWxlLmV4cG9ydHMgPSB7XG4gIHN0YWNrXG59XG4iXX0=
//# sourceURL=/usr/local/server/git/github/ws-rmi/src/test/examples/index.coffee