// Generated by CoffeeScript 2.7.0
(function() {
  //!/usr/bin/env coffee

  //  file: /src/test/index.coffee
  //  package: ws-rmi

  var examples, ipc, options, remote;

  options = require('./options');

  examples = require('./examples');

  ipc = require('./ipc');

  remote = require('./remote');

  module.exports = {ipc, remote, options, examples};

}).call(this);
