// Generated by CoffeeScript 2.7.0
(function() {
  // -*- coffee -*-

  //  file: /src/test/proxy.coffee
  //  package: ws-rmi

  var RMI_Connection, RMI_Proxy, Test_Proxy, options_choices;

  ({RMI_Proxy, RMI_Connection} = require('../lib'));

  options_choices = require('./options');

  Test_Proxy = class Test_Proxy extends RMI_Proxy {
    constructor(type = 'ipc_proxy') {
      super({
        options: options_choices[type]
      });
      this.type = type;
    }

  };

  module.exports = {Test_Proxy};

}).call(this);
