// Generated by CoffeeScript 2.4.1
(function() {
  //!/usr/bin/env coffee

  // src/examples/web/client.coffee

  var Client, client, options;

  ({Client} = require('../stack-rmi'));

  options = require('../settings').remote_options;

  client = new Client(options);

  window.client = client;

}).call(this);
