// Generated by CoffeeScript 2.4.1
(function() {
  //!/usr/bin/env coffee
  var client, server;

  client = require('./client');

  server = require('./server');

  exports.client = client;

  exports.server = server;

}).call(this);
