// Generated by CoffeeScript 2.4.1
(function() {
  //!/usr/bin/env coffee

  // src/examples/web/server.coffee

  var Server, options, server;

  ({Server} = require('../stack-rmi'));

  options = require('../settings').ipc_options;

  server = new Server(options);

  module.exports = server;

}).call(this);
