// Generated by CoffeeScript 2.7.0
(function() {
  // -*- coffee -*-

  //  file: /src/server/rmi_server.coffee
  //  package: ws-rmi

  var Logger, RMI_Connection, RMI_Object_Registry, RMI_Server, fs, http, https, process, random_id, userid, ws;

  process = require('process');

  userid = require('userid');

  fs = require('fs');

  ws = require('ws');

  http = require('http');

  https = require('https');

  
  ({random_id, Logger, RMI_Connection, RMI_Object_Registry} = require('./rmi_client_nodep'));

  // An instance of RMI_Server provides remote method invocation (RMI)
  // services for its @objects to clients connected by a websocket.

  RMI_Server = class RMI_Server {
    // @objects: an array of remotable objects

    // @options: options for the http(s) server and for logging etc.

    // Connection: a connection class extending RMI_Connection.
    // It defaults to RMI_Connection.  A subclass can be used to provide
    // extra functionality particular to the type of rmi objects being served.
    // At this point the only known reason for providing this option is for
    // the db_rmi stuff which required additional setup after @init_stubs().
    // It seems like this might frequently be the case though...

    constructor({objects, options, Socket, Connection}) {
      var ref, ref1, ref2, ref3, ref4;
      //-----------------------------------------------------------------------
      // Methods
      this.add_connection = this.add_connection.bind(this);
      this.remove_connection = this.remove_connection.bind(this);
      this.add_object = this.add_object.bind(this);
      this.del_object = this.del_object.bind(this);
      this.update_registry = this.update_registry.bind(this);
      // Method start()
      // Start the server.

      this.start = this.start.bind(this);
      this.cleanup = this.cleanup.bind(this);
      // Method stop()
      // Stop the server.

      // TODO: stop() should be called before exiting. Isn't there a way to do
      // automatic cleanup?  Or am I thinking of Python or something else?

      this.stop = this.stop.bind(this);
      this.id = random_id(this);
      this.objects = objects || {};
      this.options = options || {};
      this.Socket = Socket || null;
      this.Connection = Connection || RMI_Connection;
      this.registry = new RMI_Object_Registry({
        owner: this,
        options: this.options
      });
      this.logger = new Logger(this, {
        threshold: 2,
        options: options
      });
      this.log = this.logger.log;
      // connections added here as they are created
      this.connections = {};
      // default to 'ws+unix'
      this.protocol = ((ref = this.options) != null ? ref.protocol : void 0) || 'ws+unix';
      //-----------------------------------------------------------------------
      // system event handlers

      // Catch 'exit' (Ctrl-D)
      process.on('exit', () => {
        return this.log("RMI_Server: received 'exit' (Ctrl-D)");
      });
      // Catch 'SIGQUIT'
      //@stop()
      process.on('SIGQUIT', () => {
        return this.log("RMI_Server: received 'SIGQUIT'");
      });
      // Catch 'SIGINT' (Ctrl-C)
      process.on('SIGINT', () => {
        this.log("RMI_Server: received 'SIGINT' (Ctrl-C)");
        this.stop();
        return process.exit();
      });
      //-----------------------------------------------------------------------
      // set url according to protocol

      // Protocol 'ws+unix' means IPC (inter process communication),
      // basically unix domain sockets (or something similar in
      // Windows). See docs for npm package ws.

      if (this.protocol === 'ws+unix') {
        this.path = ((ref1 = this.options) != null ? ref1.path : void 0) || '/tmp/ipc_rmi';
        this.url = `ws+unix://${this.path}`;
      } else {
        // if fs.existsSync(@path)
        //   fs.unlinkSync(@path)
        //   process.exit())

        // Otherwise we need the usual TCP options.
        this.host = ((ref2 = this.options) != null ? ref2.host : void 0) || localhost;
        this.port = ((ref3 = this.options) != null ? ref3.port : void 0) || 8007;
        this.path = ((ref4 = this.options) != null ? ref4.path : void 0) || '';
        this.url = `${this.protocol}://${this.host}:${this.port}/${this.path}`;
      }
      //-----------------------------------------------------------------------
      // set @server according to protocol

      // wss means secure websocket so we'll use https
      if (this.protocol === 'wss') {
        this.server = new https.Server(null, this.options.credentials);
      } else {
        // otherwise just use http
        this.server = new http.Server(null);
      }
      //-----------------------------------------------------------------------
      // Create the WebSocket server providing the http(s) server
      // created just above.
      this.wss = new ws.Server({
        server: this.server
      });
      this.wss.on('connection', async(ws) => {
        var conn, error, msg;
        try {
          this.log("RMI_Server: trying new connection: ", {
            ws: ws
          });
          conn = new this.Connection(this, ws, this.options);
          this.add_connection(conn);
          return (await conn.init());
        } catch (error1) {
          error = error1;
          msg = "\nRMI_Server_Common: ";
          msg += "\nError in connection event handler";
          return new Error(msg);
        }
      });
    }

    add_connection(conn) {
      this.connections[conn.id] = conn;
      return this.log("connection added:", {
        'conn.id': conn.id
      });
    }

    remove_connection(id) {
      delete this.connections[id];
      return this.log("connection removed:", {
        'conn.id': id
      });
    }

    add_object({obj, method_names}) {
      this.objects[obj.id] = {obj, method_names};
      return this.registry.update();
    }

    del_object({id}) {
      delete this.objects[id];
      return this.registry.update();
    }

    update_registry() {
      return this.registry.update();
    }

    start() {
      var error, gid, mode, stats, uid;
      try {
        // Unix domain socket so just use @path
        if (this.protocol === 'ws+unix') {
          this.server.listen({
            path: this.path
          });
          stats = fs.statSync(this.path);
          uid = userid.uid(this.options.user);
          gid = userid.gid(this.options.group);
          mode = this.options.mode || 0o664;
          fs.chmodSync(this.path, mode);
          fs.chownSync(this.path, uid, gid);
        } else {
          // @log("fs.chownSync(#{@path}, #{uid}, #{gid})")

          // otherwise start with TCP options
          this.server.listen({
            host: this.host,
            port: this.port
          });
        }
        return this.log("RMI_Server started.", {
          url: this.url
        });
      } catch (error1) {
        error = error1;
        return this.log(error);
      }
    }

    cleanup() {
      if (fs.existsSync(this.path)) {
        fs.unlinkSync(this.path);
        return process.exit();
      }
    }

    stop() {
      this.server.close();
      return this.log("server stopped.");
    }

  };

  module.exports = {RMI_Server};

}).call(this);
