// Generated by CoffeeScript 2.7.0
(function() {
  //!/usr/bin/env coffee

  //  file: /src/server/rmi_proxy.coffee
  //  package: ws-rmi

  var Logger, RMI_Client, RMI_Connection, RMI_Proxy, RMI_Server, random_id;

  ({random_id, Logger} = require('armazilla-util'));

  ({RMI_Connection} = require('./rmi_connection'));

  ({RMI_Server} = require('./rmi_server'));

  ({RMI_Client} = require('./rmi_client'));

  RMI_Proxy = class RMI_Proxy {
    constructor({objects, options, Socket, Connection}) {
      this.add_backend = this.add_backend.bind(this);
      this.start_backend = this.start_backend.bind(this);
      this.start_backends = this.start_backends.bind(this);
      this.del_backend = this.del_backend.bind(this);
      this.id = random_id(this);
      this.objects = objects || {};
      this.options = options || {};
      this.Socket = Socket || null;
      this.Connection = Connection || RMI_Connection;
      this.server = new RMI_Server({objects: this.objects, options: this.options, Socket: this.Socket, Connection: this.Connection});
      this.backends = {};
      this.logger = new Logger(this, {
        threshold: 2,
        options: options
      });
      this.log = this.logger.log;
    }

    add_backend({options}) {
      var client, objects;
      objects = this.objects;
      client = new RMI_Client({objects, options, Socket: this.Socket, Connection: this.Connection});
      return this.backends[client.id] = client;
    }

    async start_backend(id) {
      var c, client, ref, results, stub;
      client = this.backends[id];
      c = (await client.connect());
      ref = c.stub_registry.stubs;
      results = [];
      for (id in ref) {
        stub = ref[id];
        results.push(this.server.add_object({
          obj: stub,
          method_names: stub.method_names
        }));
      }
      return results;
    }

    start_backends() {
      var client, id, ref, results;
      ref = this.backends;
      results = [];
      for (id in ref) {
        client = ref[id];
        results.push(this.start_backend(id));
      }
      return results;
    }

    del_backend(client_id) {
      var conn, id, ref, stub;
      conn = this.backend[client_id].connection;
      ref = conn.stub_registry;
      for (id in ref) {
        stub = ref[id];
        this.server.del_object({id});
      }
      return delete this.backends[client_id];
    }

  };

  module.exports = {RMI_Proxy};

}).call(this);
