// Generated by CoffeeScript 2.7.0
(function() {
  // -*- coffee -*-

  //  file: /src/client/index.coffee
  //  package: ws-rmi

  var Logger, RMI_Client, RMI_Connection, RMI_Object, RMI_Object_Registry, RMI_Stub, RMI_Stub_Registry, random_id;

  
  ({random_id, Logger, RMI_Client, RMI_Connection, RMI_Object, RMI_Object_Registry, RMI_Stub, RMI_Stub_Registry} = require('../lib/rmi_client_nodep'));

  module.exports = {random_id, Logger, RMI_Client, RMI_Connection, RMI_Object, RMI_Stub, RMI_Object_Registry, RMI_Stub_Registry};

}).call(this);
