// Generated by CoffeeScript 2.7.0
(function() {
  // -*- coffee -*-

  //  file: /src/test/nginx/server.coffee
  //  package: ws-rmi

  var RMI_Server, options, server, spec;

  ({RMI_Server} = require('../../lib'));

  options = require('../options').ipc_server;

  spec = require('../examples').stack;

  server = new RMI_Server({options});

  server.add_object({
    obj: new spec.Class(),
    method_names: spec.method_names
  });

  module.exports = server;

}).call(this);

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic2VydmVyLmpzIiwic291cmNlUm9vdCI6Ii4uLy4uLy4uLyIsInNvdXJjZXMiOlsic3JjL3Rlc3QvcmVtb3RlL3NlcnZlci5jb2ZmZWUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUlDO0VBQUE7Ozs7O0FBQUEsTUFBQSxVQUFBLEVBQUEsT0FBQSxFQUFBLE1BQUEsRUFBQTs7RUFFRCxDQUFBLENBQUUsVUFBRixDQUFBLEdBQWlCLE9BQUEsQ0FBUSxXQUFSLENBQWpCOztFQUNBLE9BQUEsR0FBVSxPQUFBLENBQVEsWUFBUixDQUFxQixDQUFDOztFQUNoQyxJQUFBLEdBQU8sT0FBQSxDQUFRLGFBQVIsQ0FBc0IsQ0FBQzs7RUFFOUIsTUFBQSxHQUFTLElBQUksVUFBSixDQUFlLENBQUUsT0FBRixDQUFmOztFQUNULE1BQU0sQ0FBQyxVQUFQLENBQWtCO0lBQ2hCLEdBQUEsRUFBSyxJQUFJLElBQUksQ0FBQyxLQUFULENBQUEsQ0FEVztJQUVoQixZQUFBLEVBQWMsSUFBSSxDQUFDO0VBRkgsQ0FBbEI7O0VBS0EsTUFBTSxDQUFDLE9BQVAsR0FBaUI7QUFaaEIiLCJzb3VyY2VzQ29udGVudCI6WyIjIC0qLSBjb2ZmZWUgLSotXG4jXG4jICBmaWxlOiAvc3JjL3Rlc3Qvbmdpbngvc2VydmVyLmNvZmZlZVxuIyAgcGFja2FnZTogd3Mtcm1pXG4jXG5cbnsgUk1JX1NlcnZlciB9ID0gcmVxdWlyZSgnLi4vLi4vbGliJylcbm9wdGlvbnMgPSByZXF1aXJlKCcuLi9vcHRpb25zJykuaXBjX3NlcnZlclxuc3BlYyA9IHJlcXVpcmUoJy4uL2V4YW1wbGVzJykuc3RhY2tcblxuc2VydmVyID0gbmV3IFJNSV9TZXJ2ZXIoeyBvcHRpb25zIH0pXG5zZXJ2ZXIuYWRkX29iamVjdCh7XG4gIG9iajogbmV3IHNwZWMuQ2xhc3MoKVxuICBtZXRob2RfbmFtZXM6IHNwZWMubWV0aG9kX25hbWVzXG4gIH0pXG5cbm1vZHVsZS5leHBvcnRzID0gc2VydmVyXG4iXX0=
//# sourceURL=/usr/local/server/git/github/ws-rmi/src/test/remote/server.coffee